server:
  port: 8081

spring:
  application:
    name: ms-cliente
  
  # Configurações do Banco de Dados H2
  datasource:
    url: jdbc:h2:mem:clientedb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Configurações do JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Configurações do Apache Kafka (Mesclado aqui)
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
